# Generated by Django 3.1.6 on 2021-02-27 07:56

from django.db import migrations
from django.contrib.auth.models import Group, Permission

def add_group_permission(apps, schema_editor):
        group, created = Group.objects.get_or_create(name='doctor')
        if created:
            pass
    


        group, created = Group.objects.get_or_create(name='patient')
        if created:
            pass


class Migration(migrations.Migration):
    

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_group_permission),

    ]
