# Generated by Django 3.1.6 on 2021-03-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210302_0749'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='watchlist',
            field=models.ManyToManyField(to='patient.Patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
