# Generated by Django 3.1.6 on 2021-03-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210302_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureobjectmatchingtest',
            name='date_time_completed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trailmakingtest',
            name='date_time_completed',
            field=models.IntegerField(),
        ),
    ]
